# fast postgres setup

version: '3'

services:

  meta-db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - demo_db_volume:/var/lib/postgresql/data
    env_file: ".env"
    ports:
      - $DB_PORT:5432

  front-builder:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/dist:/app/dist
    command: >
      sh -c "npm run serve"
    ports:
      - 8080:8080


volumes:
  demo_db_volume: {}
